#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
plot_final_thesis_s7s17_c4_parameter_histograms_1000bins.py

Purpose
-------
Create thesis-ready count histograms for the final fully synthetic S7_C4 and
S17_C4 CT-ID verification study.

This script reads the chunk outputs generated by:

    run_final_thesis_s7s17_c4_simulated_chunk.py

It does not rerun identification.

Expected input folders
----------------------
results/final_thesis_ctid_s7s17_c4_1000/final_thesis_S7_C4_chunk_*/all_runs.csv
results/final_thesis_ctid_s7s17_c4_1000/final_thesis_S17_C4_chunk_*/all_runs.csv

Expected run plan
-----------------
    S7_C4 : 10 chunks x 100 seeds = 1000 runs
    S17_C4: 10 chunks x 100 seeds = 1000 runs

Outputs
-------
results/tables/final_thesis_ctid_s7s17_c4_1000/parameter_histograms_1000bins/
    combined_all_runs_with_parameter_errors.csv
    combined_config_truth_values.csv
    parameter_histogram_summary.csv
    parameter_best_recovered_summary.csv
    run_count_audit.csv

results/figures/final_thesis_ctid_s7s17_c4_1000/parameter_histograms_1000bins/
    per_model/<model_id>/
    combined_by_parameter/
    combined_zoomed_by_parameter/
    small_multiples_by_parameter/
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt


# =====================================================================
# Paths and settings
# =====================================================================
PROJECT_DIR = Path.cwd()

RESULT_ROOT = PROJECT_DIR / "results" / "final_thesis_ctid_s7s17_c4_1000"
FIG_DIR = PROJECT_DIR / "results" / "figures" / "final_thesis_ctid_s7s17_c4_1000" / "parameter_histograms_1000bins"
TABLE_DIR = PROJECT_DIR / "results" / "tables" / "final_thesis_ctid_s7s17_c4_1000" / "parameter_histograms_1000bins"

FIG_PER_MODEL_DIR = FIG_DIR / "per_model"
FIG_COMBINED_DIR = FIG_DIR / "combined_by_parameter"
FIG_COMBINED_ZOOM_DIR = FIG_DIR / "combined_zoomed_by_parameter"
FIG_SMALL_MULTIPLE_DIR = FIG_DIR / "small_multiples_by_parameter"

for p in [FIG_DIR, TABLE_DIR, FIG_PER_MODEL_DIR, FIG_COMBINED_DIR, FIG_COMBINED_ZOOM_DIR, FIG_SMALL_MULTIPLE_DIR]:
    p.mkdir(parents=True, exist_ok=True)

MODEL_ORDER = ["S7_C4", "S17_C4"]
MODEL_LABELS = {
    "S7_C4": "S7 C4",
    "S17_C4": "S17 C4",
}

HIST_BINS = int(float(os.environ.get("UN_HIST_BINS", "1000")))
EXPECTED_RUNS_PER_MODEL = int(os.environ.get("UN_EXPECTED_RUNS_PER_MODEL", "1000"))
EXPECTED_TOTAL_RUNS = EXPECTED_RUNS_PER_MODEL * len(MODEL_ORDER)

INCLUDE_BETA_PARAMETERS = os.environ.get("UN_INCLUDE_BETA_PARAMETERS", "False").lower() == "true"
INCLUDE_EDGE_K_PARAMETERS = os.environ.get("UN_INCLUDE_EDGE_K_PARAMETERS", "True").lower() == "true"

ZOOM_LOW_Q = float(os.environ.get("UN_ZOOM_LOW_Q", "0.01"))
ZOOM_HIGH_Q = float(os.environ.get("UN_ZOOM_HIGH_Q", "0.99"))

BASE_PARAMETER_COLUMNS = [
    "alpha_n_hat",
    "alpha_p_hat",
    "g_n_hat",
    "g_p_hat",
    "b_en_hat",
    "b_ep_hat",
    "k1_hat",
    "k2_hat",
    "k3_hat",
    "k4_hat",
    "k5_hat",
]

EDGE_K_COLUMNS = [f"k_edge{i}_hat" for i in range(1, 9)]


# =====================================================================
# Helpers
# =====================================================================
def infer_model_from_folder_name(name: str) -> str | None:
    m = re.search(r"final_thesis_(S(?:7|17)_C4)_chunk", name)
    if m:
        return m.group(1)
    return None


def infer_chunk_from_folder_name(name: str) -> int | None:
    m = re.search(r"_chunk_(\d+)_", name)
    if m:
        return int(m.group(1))
    return None


def model_sort_key(mid: str) -> int:
    try:
        return MODEL_ORDER.index(str(mid))
    except ValueError:
        return 999


def model_label(mid: str) -> str:
    return MODEL_LABELS.get(str(mid), str(mid))


def savefig(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(path, dpi=280, bbox_inches="tight")
    print("[saved figure]", path)
    plt.close()


def safe_filename(text: str) -> str:
    return (
        str(text)
        .replace("^", "pow")
        .replace("-", "minus")
        .replace("+", "plus")
        .replace("/", "_")
        .replace(" ", "_")
        .replace("(", "")
        .replace(")", "")
        .replace("[", "")
        .replace("]", "")
        .replace("%", "percent")
    )


def relative_error_percent(true_value: float, estimate: float) -> float:
    denom = max(abs(float(true_value)), 1e-15)
    return 100.0 * abs(float(estimate) - float(true_value)) / denom


def finite_values(series: pd.Series) -> np.ndarray:
    x = pd.to_numeric(series, errors="coerce").to_numpy(dtype=float)
    return x[np.isfinite(x)]


def choose_plot_range(x: np.ndarray, low_q: float = 0.01, high_q: float = 0.99) -> tuple[float, float]:
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if len(x) == 0:
        return np.nan, np.nan
    lo = float(np.quantile(x, low_q))
    hi = float(np.quantile(x, high_q))
    if not np.isfinite(lo) or not np.isfinite(hi) or lo == hi:
        lo = float(np.min(x))
        hi = float(np.max(x))
    if lo == hi:
        pad = abs(lo) * 0.01 + 1e-12
        lo -= pad
        hi += pad
    return lo, hi


def get_best_recovered(values: np.ndarray, true_value: float) -> tuple[float, int, float]:
    values = np.asarray(values, dtype=float)
    mask = np.isfinite(values)
    if not np.any(mask):
        return np.nan, -1, np.nan
    finite_vals = values[mask]
    finite_indices = np.where(mask)[0]
    errors = np.array([relative_error_percent(true_value, v) for v in finite_vals])
    j = int(np.argmin(errors))
    return float(finite_vals[j]), int(finite_indices[j]), float(errors[j])


def safe_load_config(config_path: Path) -> dict[str, Any]:
    if not config_path.exists():
        return {}
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        print("[warn] could not parse config:", config_path, repr(exc))
        return {}


def get_truth_values_from_config(config_path: Path | None) -> dict[str, float]:
    """Return truth values keyed by all_runs column names."""
    truth: dict[str, float] = {}
    payload = safe_load_config(config_path) if config_path is not None else {}

    t = payload.get("truth", {}) if isinstance(payload, dict) else {}

    # Preferred new location from the synthetic S7/S17 runner.
    ptv = t.get("parameter_truth_values", {}) if isinstance(t, dict) else {}
    if isinstance(ptv, dict):
        for k, v in ptv.items():
            try:
                truth[str(k)] = float(v)
            except Exception:
                pass

    # Fallbacks for the main physical parameters.
    fallback_map = {
        "alpha_n_hat": "alpha_n_true",
        "alpha_p_hat": "alpha_p_true",
        "g_n_hat": "g_n_true",
        "g_p_hat": "g_p_true",
        "b_en_hat": "b_en_true",
        "b_ep_hat": "b_ep_true",
        "theta_n0_fixed": "theta_n0_true",
        "theta_p0_fixed": "theta_p0_true",
    }
    for out_col, truth_key in fallback_map.items():
        if out_col not in truth and truth_key in t:
            try:
                truth[out_col] = float(t[truth_key])
            except Exception:
                pass

    if "k_ind_true" in t and isinstance(t["k_ind_true"], list):
        for i, val in enumerate(t["k_ind_true"], start=1):
            truth.setdefault(f"k{i}_hat", float(val))
    if "k_edges_true" in t and isinstance(t["k_edges_true"], list):
        for i, val in enumerate(t["k_edges_true"], start=1):
            truth.setdefault(f"k_edge{i}_hat", float(val))

    beta_true = t.get("beta_true", {}) if isinstance(t, dict) else {}
    if isinstance(beta_true, dict):
        for name, val in beta_true.items():
            safe = str(name).replace("^", "pow").replace("-", "minus").replace(" ", "_")
            try:
                truth.setdefault(f"beta_{safe}", float(val))
            except Exception:
                pass

    return truth


# =====================================================================
# Load chunk outputs
# =====================================================================
if not RESULT_ROOT.exists():
    raise RuntimeError(f"Result root does not exist: {RESULT_ROOT}")

chunk_dirs = sorted(
    [
        p for p in RESULT_ROOT.glob("final_thesis_S*_C4_chunk_*")
        if p.is_dir() and (p / "all_runs.csv").exists()
    ]
)

if not chunk_dirs:
    raise RuntimeError(
        f"No all_runs.csv files found under {RESULT_ROOT}. "
        "Expected folders like final_thesis_S7_C4_chunk_0_... and final_thesis_S17_C4_chunk_0_..."
    )

all_frames = []
config_rows = []

for folder in chunk_dirs:
    model_id = infer_model_from_folder_name(folder.name)
    chunk_index = infer_chunk_from_folder_name(folder.name)
    all_path = folder / "all_runs.csv"
    config_path = folder / "config.json"

    df = pd.read_csv(all_path)

    if "model_id" not in df.columns or df["model_id"].isna().all():
        df["model_id"] = model_id
    if "state_id" not in df.columns:
        df["state_id"] = df["model_id"].astype(str).str.replace("_C4", "", regex=False)

    df["model_id"] = df["model_id"].astype(str)
    df["chunk_index"] = chunk_index
    df["chunk_folder"] = folder.name
    df["source_folder"] = str(folder)
    all_frames.append(df)

    truth = get_truth_values_from_config(config_path if config_path.exists() else None)
    config_rows.append(
        {
            "model_id": model_id,
            "chunk_index": chunk_index,
            "chunk_folder": folder.name,
            "config_path": str(config_path) if config_path.exists() else "",
            **{f"truth_{k}": v for k, v in truth.items()},
        }
    )

all_runs = pd.concat(all_frames, ignore_index=True)
config_table = pd.DataFrame(config_rows)
all_runs["model_id"] = all_runs["model_id"].astype(str)
all_runs["model_sort"] = all_runs["model_id"].map(model_sort_key)
all_runs = all_runs.sort_values(["model_sort", "chunk_index", "seed"]).reset_index(drop=True)

parameter_columns = list(BASE_PARAMETER_COLUMNS)
if INCLUDE_EDGE_K_PARAMETERS:
    parameter_columns += EDGE_K_COLUMNS

# Keep only columns that exist at least once.
parameter_columns = [c for c in parameter_columns if c in all_runs.columns]

if INCLUDE_BETA_PARAMETERS:
    beta_cols = [c for c in all_runs.columns if c.startswith("beta_")]
    parameter_columns += [c for c in beta_cols if c not in parameter_columns]

print("=" * 100)
print("Loaded final thesis S7/S17 C4 synthetic CT-ID results")
print("=" * 100)
print("Chunk folders found:", len(chunk_dirs))
print("Total rows loaded:", len(all_runs))
print("Histogram bins:", HIST_BINS)
print("Parameters:", parameter_columns)
print("=" * 100)


# =====================================================================
# Completion audit
# =====================================================================
audit_rows = []
for mid in MODEL_ORDER:
    g = all_runs[all_runs["model_id"] == mid]
    chunks = sorted(g["chunk_index"].dropna().astype(int).unique().tolist())
    audit_rows.append(
        {
            "model_id": mid,
            "expected_runs": EXPECTED_RUNS_PER_MODEL,
            "found_runs": int(len(g)),
            "missing_runs": int(EXPECTED_RUNS_PER_MODEL - len(g)),
            "found_chunks": len(chunks),
            "chunk_indices": ",".join(map(str, chunks)),
            "complete": bool(len(g) == EXPECTED_RUNS_PER_MODEL),
        }
    )

audit = pd.DataFrame(audit_rows)
total_row = pd.DataFrame(
    [
        {
            "model_id": "TOTAL",
            "expected_runs": EXPECTED_TOTAL_RUNS,
            "found_runs": int(len(all_runs)),
            "missing_runs": int(EXPECTED_TOTAL_RUNS - len(all_runs)),
            "found_chunks": int(audit["found_chunks"].sum()),
            "chunk_indices": "",
            "complete": bool(len(all_runs) == EXPECTED_TOTAL_RUNS),
        }
    ]
)
audit_full = pd.concat([audit, total_row], ignore_index=True)
audit_full.to_csv(TABLE_DIR / "run_count_audit.csv", index=False)
print("\nRun count audit:")
print(audit_full.to_string(index=False))


# =====================================================================
# Truth values and parameter errors
# =====================================================================
truth_by_model: dict[str, dict[str, float]] = {}
for mid in MODEL_ORDER:
    cfg_rows = config_table[config_table["model_id"] == mid]
    if len(cfg_rows):
        row = cfg_rows.iloc[0]
        truth_by_model[mid] = {
            str(k).replace("truth_", ""): float(row[k])
            for k in row.index
            if str(k).startswith("truth_") and pd.notna(row[k])
        }
    else:
        truth_by_model[mid] = {}

for mid in MODEL_ORDER:
    mask = all_runs["model_id"] == mid
    truth = truth_by_model.get(mid, {})
    for param in parameter_columns:
        if param not in all_runs.columns or param not in truth:
            continue
        if param.endswith("_hat"):
            err_col = param.replace("_hat", "_error_percent")
        elif param.endswith("_fixed"):
            err_col = param.replace("_fixed", "_error_percent")
        else:
            err_col = f"{param}_error_percent"
        all_runs.loc[mask, err_col] = all_runs.loc[mask, param].apply(
            lambda x: relative_error_percent(truth[param], x) if pd.notna(x) else np.nan
        )

all_runs.to_csv(TABLE_DIR / "combined_all_runs_with_parameter_errors.csv", index=False)
config_table.to_csv(TABLE_DIR / "combined_config_truth_values.csv", index=False)


# =====================================================================
# Summary tables
# =====================================================================
summary_rows = []
best_rows = []

for mid in MODEL_ORDER:
    g = all_runs[all_runs["model_id"] == mid].copy()
    truth = truth_by_model.get(mid, {})
    if len(g) == 0:
        continue

    for param in parameter_columns:
        if param not in g.columns:
            continue
        x = finite_values(g[param])
        if len(x) == 0:
            continue
        true_value = truth.get(param, np.nan)
        mean_value = float(np.mean(x))
        median_value = float(np.median(x))
        std_value = float(np.std(x, ddof=1)) if len(x) > 1 else np.nan
        q01 = float(np.quantile(x, 0.01))
        q05 = float(np.quantile(x, 0.05))
        q25 = float(np.quantile(x, 0.25))
        q75 = float(np.quantile(x, 0.75))
        q95 = float(np.quantile(x, 0.95))
        q99 = float(np.quantile(x, 0.99))

        if np.isfinite(true_value):
            best_value, _, best_error = get_best_recovered(x, true_value)
        else:
            best_value, best_error = np.nan, np.nan

        candidate_rows = g[np.isfinite(pd.to_numeric(g[param], errors="coerce"))].copy()
        if len(candidate_rows) and np.isfinite(true_value):
            candidate_rows["_param_abs_error"] = candidate_rows[param].apply(
                lambda v: abs(float(v) - true_value) if pd.notna(v) else np.nan
            )
            best_row = candidate_rows.sort_values("_param_abs_error").head(1)
        elif len(candidate_rows):
            best_row = candidate_rows.sort_values("rmse").head(1)
        else:
            best_row = pd.DataFrame()

        if len(best_row):
            best_seed = int(best_row["seed"].iloc[0]) if "seed" in best_row.columns and pd.notna(best_row["seed"].iloc[0]) else np.nan
            best_rmse = float(best_row["rmse"].iloc[0]) if "rmse" in best_row.columns and pd.notna(best_row["rmse"].iloc[0]) else np.nan
            best_chunk = int(best_row["chunk_index"].iloc[0]) if "chunk_index" in best_row.columns and pd.notna(best_row["chunk_index"].iloc[0]) else np.nan
        else:
            best_seed = np.nan
            best_rmse = np.nan
            best_chunk = np.nan

        summary_rows.append(
            {
                "model_id": mid,
                "model_label": model_label(mid),
                "parameter": param,
                "n": int(len(x)),
                "true_value": true_value,
                "mean": mean_value,
                "median": median_value,
                "std": std_value,
                "q01": q01,
                "q05": q05,
                "q25": q25,
                "q75": q75,
                "q95": q95,
                "q99": q99,
                "mean_error_percent": relative_error_percent(true_value, mean_value) if np.isfinite(true_value) else np.nan,
                "median_error_percent": relative_error_percent(true_value, median_value) if np.isfinite(true_value) else np.nan,
                "best_recovered_value": best_value,
                "best_recovered_error_percent": best_error,
                "best_recovered_seed": best_seed,
                "best_recovered_chunk": best_chunk,
                "best_recovered_run_rmse": best_rmse,
            }
        )

        best_rows.append(
            {
                "model_id": mid,
                "parameter": param,
                "true_value": true_value,
                "best_recovered_value": best_value,
                "best_recovered_error_percent": best_error,
                "best_recovered_seed": best_seed,
                "best_recovered_chunk": best_chunk,
                "best_recovered_run_rmse": best_rmse,
            }
        )

summary = pd.DataFrame(summary_rows)
best_summary = pd.DataFrame(best_rows)
summary.to_csv(TABLE_DIR / "parameter_histogram_summary.csv", index=False)
best_summary.to_csv(TABLE_DIR / "parameter_best_recovered_summary.csv", index=False)
print("\nParameter summary saved:", TABLE_DIR / "parameter_histogram_summary.csv")


# =====================================================================
# Per-model histograms
# =====================================================================
for mid in MODEL_ORDER:
    g = all_runs[all_runs["model_id"] == mid].copy()
    if len(g) == 0:
        continue
    model_dir = FIG_PER_MODEL_DIR / mid
    model_dir.mkdir(parents=True, exist_ok=True)

    for param in parameter_columns:
        if param not in g.columns:
            continue
        x = finite_values(g[param])
        if len(x) == 0:
            continue
        srow = summary[(summary["model_id"] == mid) & (summary["parameter"] == param)]
        if len(srow) == 0:
            continue
        srow = srow.iloc[0]
        true_value = float(srow["true_value"])
        mean_value = float(srow["mean"])
        median_value = float(srow["median"])
        best_value = float(srow["best_recovered_value"])

        plt.figure(figsize=(9.8, 5.8))
        plt.hist(x, bins=HIST_BINS, density=False, edgecolor="black", linewidth=0.25, alpha=0.78)
        if np.isfinite(true_value):
            plt.axvline(true_value, linestyle="-", linewidth=2.6, label=f"true = {true_value:.6g}")
        if np.isfinite(mean_value):
            plt.axvline(mean_value, linestyle="--", linewidth=2.2, label=f"mean = {mean_value:.6g}")
        if np.isfinite(median_value):
            plt.axvline(median_value, linestyle=":", linewidth=2.6, label=f"median = {median_value:.6g}")
        if np.isfinite(best_value):
            plt.axvline(best_value, linestyle="-.", linewidth=2.2, label=f"best recovered = {best_value:.6g}")
        plt.grid(True, axis="y", alpha=0.35)
        plt.xlabel(f"Recovered {param}")
        plt.ylabel("Count of simulations")
        plt.title(f"{model_label(mid)}: recovered {param} ({HIST_BINS} bins, n={len(x)})")
        plt.legend(loc="best", fontsize=8)
        plt.tight_layout()
        savefig(model_dir / f"hist_{safe_filename(param)}_{HIST_BINS}bins.png")


# =====================================================================
# Combined overlay histograms
# =====================================================================
def plot_combined_parameter_histogram(param: str, out_path: Path, zoom: bool = False) -> None:
    xs = []
    for mid in MODEL_ORDER:
        g = all_runs[all_runs["model_id"] == mid]
        if param not in g.columns:
            continue
        x = finite_values(g[param])
        if len(x):
            xs.append(x)
    if not xs:
        return

    all_x = np.concatenate(xs)
    if zoom:
        lo, hi = choose_plot_range(all_x, ZOOM_LOW_Q, ZOOM_HIGH_Q)
    else:
        lo, hi = float(np.min(all_x)), float(np.max(all_x))
    if lo == hi:
        pad = abs(lo) * 0.01 + 1e-12
        lo -= pad
        hi += pad
    bins = np.linspace(lo, hi, HIST_BINS + 1)

    plt.figure(figsize=(10.5, 6.2))
    for mid in MODEL_ORDER:
        g = all_runs[all_runs["model_id"] == mid]
        if param not in g.columns:
            continue
        x = finite_values(g[param])
        x = x[(x >= lo) & (x <= hi)]
        if len(x) == 0:
            continue
        plt.hist(x, bins=bins, density=False, histtype="step", linewidth=1.8, label=f"{model_label(mid)}, n={len(x)}")

    truth_candidates = [truth_by_model[mid].get(param, np.nan) for mid in MODEL_ORDER if param in truth_by_model.get(mid, {})]
    finite_truth = [v for v in truth_candidates if np.isfinite(v)]
    if finite_truth:
        # If both models share the same truth value, draw one true line.
        # If not, draw separate true lines in the per-model plots and use the first here.
        true_value = float(finite_truth[0])
        plt.axvline(true_value, linestyle="-", linewidth=3.0, label=f"true = {true_value:.6g}")

    plt.grid(True, axis="y", alpha=0.35)
    plt.xlabel(f"Recovered {param}")
    plt.ylabel("Count of simulations")
    suffix = "zoomed q01-q99" if zoom else "full range"
    plt.title(f"Combined S7/S17 histogram for {param} ({suffix}, {HIST_BINS} bins)")
    plt.legend(loc="best", fontsize=8)
    plt.tight_layout()
    savefig(out_path)


for param in parameter_columns:
    plot_combined_parameter_histogram(
        param=param,
        out_path=FIG_COMBINED_DIR / f"combined_hist_{safe_filename(param)}_{HIST_BINS}bins.png",
        zoom=False,
    )
    plot_combined_parameter_histogram(
        param=param,
        out_path=FIG_COMBINED_ZOOM_DIR / f"combined_hist_{safe_filename(param)}_zoom_q01_q99_{HIST_BINS}bins.png",
        zoom=True,
    )


# =====================================================================
# Small multiples: one figure per parameter, S7 and S17 panels
# =====================================================================
def plot_small_multiple_parameter(param: str, out_path: Path, zoom: bool = True) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(14, 5.2), sharey=False)
    axes = np.asarray(axes).reshape(-1)

    all_x_list = []
    for mid in MODEL_ORDER:
        g = all_runs[all_runs["model_id"] == mid]
        if param not in g.columns:
            continue
        x = finite_values(g[param])
        if len(x):
            all_x_list.append(x)
    if not all_x_list:
        plt.close(fig)
        return

    all_x = np.concatenate(all_x_list)
    if zoom:
        lo, hi = choose_plot_range(all_x, ZOOM_LOW_Q, ZOOM_HIGH_Q)
    else:
        lo, hi = float(np.min(all_x)), float(np.max(all_x))
    if lo == hi:
        pad = abs(lo) * 0.01 + 1e-12
        lo -= pad
        hi += pad
    bins = np.linspace(lo, hi, HIST_BINS + 1)

    for ax, mid in zip(axes, MODEL_ORDER):
        g = all_runs[all_runs["model_id"] == mid]
        if param not in g.columns or len(g) == 0:
            ax.set_title(f"{model_label(mid)}: no data")
            continue
        x = finite_values(g[param])
        x = x[(x >= lo) & (x <= hi)]
        srow = summary[(summary["model_id"] == mid) & (summary["parameter"] == param)]
        if len(srow) == 0:
            ax.set_title(f"{model_label(mid)}: no summary")
            continue
        srow = srow.iloc[0]
        ax.hist(x, bins=bins, density=False, histtype="bar", edgecolor="black", linewidth=0.20, alpha=0.78)
        true_value = float(srow["true_value"])
        mean_value = float(srow["mean"])
        median_value = float(srow["median"])
        best_value = float(srow["best_recovered_value"])
        if np.isfinite(true_value):
            ax.axvline(true_value, linestyle="-", linewidth=2.6, label="true")
        if np.isfinite(mean_value):
            ax.axvline(mean_value, linestyle="--", linewidth=2.2, label="mean")
        if np.isfinite(median_value):
            ax.axvline(median_value, linestyle=":", linewidth=2.6, label="median")
        if np.isfinite(best_value):
            ax.axvline(best_value, linestyle="-.", linewidth=2.2, label="best recovered")
        ax.grid(True, axis="y", alpha=0.35)
        ax.set_title(model_label(mid))
        ax.set_xlabel(param)
        ax.set_ylabel("Count")
        ax.legend(loc="best", fontsize=7)

    title_suffix = "zoomed q01-q99" if zoom else "full range"
    fig.suptitle(f"Recovered {param} histograms by model ({title_suffix}, {HIST_BINS} bins)", fontsize=14)
    fig.tight_layout(rect=[0, 0, 1, 0.93])
    savefig(out_path)


for param in parameter_columns:
    plot_small_multiple_parameter(
        param=param,
        out_path=FIG_SMALL_MULTIPLE_DIR / f"small_multiple_{safe_filename(param)}_zoom_q01_q99_{HIST_BINS}bins.png",
        zoom=True,
    )
    plot_small_multiple_parameter(
        param=param,
        out_path=FIG_SMALL_MULTIPLE_DIR / f"small_multiple_{safe_filename(param)}_full_{HIST_BINS}bins.png",
        zoom=False,
    )


print("\n" + "=" * 100)
print("S7/S17 C4 PARAMETER HISTOGRAMS COMPLETE")
print("=" * 100)
print("Histogram bins:", HIST_BINS)
print("Tables saved to:", TABLE_DIR)
print("Figures saved to:", FIG_DIR)
print("\nImportant folders:")
print("  Per-model histograms:", FIG_PER_MODEL_DIR)
print("  Combined overlays:", FIG_COMBINED_DIR)
print("  Combined zoomed overlays:", FIG_COMBINED_ZOOM_DIR)
print("  Small multiples:", FIG_SMALL_MULTIPLE_DIR)
print("\nImportant tables:")
print(" ", TABLE_DIR / "combined_all_runs_with_parameter_errors.csv")
print(" ", TABLE_DIR / "parameter_histogram_summary.csv")
print(" ", TABLE_DIR / "parameter_best_recovered_summary.csv")
print(" ", TABLE_DIR / "run_count_audit.csv")
print("=" * 100)
